config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  resources :lists do
    resources :bookmarks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [ :new, :create ]
  def index
    @bookmarks = Bookmark.all
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmarks_params)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to new_list_bookmark_path(@bookmark)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmarks_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(lists_params)
    @list.save
    redirect_to lists_path
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def lists_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<div class="container form">
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>
</div>

app/views/bookmarks/new.html.erb
<div class="container">
<h1>Add a new Bookmark</h1>
<%= render "form", bookmark: @bookmark, list: @list %>
</div>

app/views/bookmarks/show.html.erb
<div class="container">
<h1>Hi</h1>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.label :Name %>
  <%= f.text_field :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<div class="container">
<h1>Lists</h1>

<div id="lists">
  <% @lists.each do |name| %>
    <p>
      <%= link_to name.name, list_path(name) %>
    </p>
  <% end %>
</div>

<button><%= link_to "Add new List", new_list_path %></button>
</div>

app/views/lists/new.html.erb
<div class="container">
<h1>Add new List</h1>
<%= render "form", list: @list %>
</div>

app/views/lists/show.html.erb
<div class="container">
<h1>List Details</h1>
<p class="underline" ><%= @list.name %></p>

<p><%= link_to "Return to Lists", lists_path %></p>
<%= cl_image_tag @list.photo.key, height: 200, width: 200, crop: :fill %>
<p><%= link_to "Add new Bookmark", new_list_bookmark_path(@list) %></p>
</div>